name: Azure

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - name: Build
        run: mvn -B package --file pom.xml
      - name: Azure Login
        uses: azure/login@v1
        with:
          # See: https://github.com/Azure/webapps-deploy#configure-deployment-credentials-1
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy
        # See: https://github.com/Azure/webapps-deploy/issues/49
        run: >
          az webapp deploy
          --resource-group ${{ secrets.AZURE_WEBAPP_RESOURCE_GROUP }}
          --name ${{ secrets.AZURE_WEBAPP_APP_NAME }}
          --src-path ./target/*.war
          --type war
